name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check protoc
        run: protoc --version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Lint
        run: cargo lint

      - name: Test
        run: cargo test
